# Generated by Django 4.1.1 on 2023-02-20 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
            ],
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('no', models.CharField(blank=True, max_length=100, null=True, verbose_name='单号')),
                ('shop', models.CharField(max_length=200, verbose_name='商户')),
                ('shop_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='商户编号')),
                ('sku', models.CharField(max_length=300, verbose_name='商品')),
                ('status', models.SmallIntegerField(choices=[(1, '已支付'), (2, '未支付')], default=1, verbose_name='支付状态')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hehe.user', verbose_name='消费者')),
            ],
        ),
    ]
