# Generated by Django 4.1.1 on 2023-02-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hehe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=128, verbose_name='上传图片')),
            ],
        ),
    ]
